version: 0.1.{build}

image: Visual Studio 2015

environment:
  matrix:
    # Python 3.6.6 - 64-bit
    - PYTHON: "C:\\Python36-x64"

#---------------------------------#
#        Build                    #
#---------------------------------#

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;C:\MinGW\bin
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - copy c:\Python36-x64\python.exe c:\Python36-x64\python3.exe
  - python --version
  - make install
  - make package
  - copy /Y dist\DEXBot-gui.exe installer\windows\msi\DEXBot.exe
  - '7z a DEXBot-gui-win64.zip %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-gui.exe'
  # Read dexbot version from __init__.py
  - ps:  Get-Content __init__.py | Foreach-Object { $var = $_.Split('='); echo $var[0].Trim(); echo $var[1].Trim(); if($var[0].Trim() -eq 'VERSION') { $env:VERSION=$var[1].Trim(); }}
  - echo %VERSION%
  # Set to version and replace ' with empty character
  - set ApplicationVersion=%VERSION:'=%
  - echo %ApplicationVersion%

# Visual studio configuration
configuration:
- Release
platform: x86
build:
  verbosity: normal

# @TODO: Run tests..
test_script:
  - "echo tests..."

# Artifacts as relative path to the build folder C:\projects\dexbot
artifacts:
  - path: DEXBot-gui-win64.zip
    name: DEXBot-gui-win64-%ApplicationVersion%.zip
  - path: installer\windows\bundle\bin\%CONFIGURATION%\DEXBot-installer.exe
    name: DEXBot-installer-%ApplicationVersion%.exe

#---------------------------------#
#        Deployment               #
#---------------------------------#

shallow_clone: false

clone_depth: 1

deploy:
  - provider: GitHub
    draft: false
    prerelease: false
    force_update: true
    auth_token:
      secure: 9qvwlVUHFBV4GwMz1Gu2HSnqU8Ex2nv5dsY4mVNCurrb+6ULIoHPgbvJPWTo3qV6
    on:
      appveyor_repo_tag: true     # Deploy on tag push only

#---------------------------------#
#         Notifications           #
#---------------------------------#

notifications:
  - provider: Slack
    auth_token:
      secure: G9OMj9l2s3+lX8cRiNXXhuQJpnnjcBc0cqP8gzkdKVWqGA8vBTOIPGxD/536VKpeBH/5dJFQWT+vmnGS+XciaCg4hh5s6hDpnvePq2+uEYE=
    channel: '#ci'
