witness_url: "ws://testnet.bitshares.eu/ws"
prefix: "TEST"
safe_mode: True
account: "xeroc"
wif: "5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

market_separator: ":"

reserves:
 BTS: 1000
 USD: 10

bots:
    MakerWall:
        module: "stakemachine.strategies.maker"
        bot: "MakerSellBuyWalls"
        markets:
            - "TEMPA:LIVE"
        target_price: "last"
        target_price_offset_percentage: 0
        spread_percentage: 5
        volume_percentage: 10
        symmetric_sides: True
        only_buy: False
        only_sell: False

    MakerWall2:
        module: "stakemachine.strategies.maker"
        bot: "MakerSellBuyWalls"
        markets:
            - "TEMPA:LIVE"
        target_price: "last"
        target_price_offset_percentage: 0
        spread_percentage: 15
        volume_percentage: 20
        symmetric_sides: True
        only_buy: False
        only_sell: False
